config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  # get '/help', to: 'static_pages#help'
  match '/help', to: 'static_pages#help', via: :get
  get '/about', to: 'static_pages#about', as: :about
  get '/contact', to: 'static_pages#contact'

  resources :users do
    member do
      get :following, :followers
    end
  end

  get '/signup', to: 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href='https://www.intuit.ru/studies/courses/10474/1081/info'>Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Contact', contact_path %></li>
      <li><%= link_to 'News', 'https://www.intuit.ru/news' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'Sample App', root_url, id: 'logo' %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Help', help_path %></li>
          <% if signed_in? %>
            <li><%= link_to 'Users', users_path %></li>
            <li id="fat_menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'Sign out', signout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Sign in', signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |k, v| %>
      <%= content_tag(:div, v, class: "alert alert-#{k}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>